server:
  port: 8083
spring:
  datasource:
    username: xhynpxlcgdusvs
    password: 746bc84001cbee024e1f54e5dda092ac7b994bc4bf402cdb9076f25652c8cebc
    url: jdbc:postgresql://ec2-54-171-193-12.eu-west-1.compute.amazonaws.com:5432/d8ma33m72anskp?currentSchema=libria
  jpa:
    open-in-view: 'false'
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      mode: always

  liquibase:
    enabled: true
    change-log: classpath:liquibase-changeLog.xml
